version: '3.8'

services:
  calorie-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend API
      - "8080:8080"  # Frontend server
    volumes:
      - ./backend/uploads:/app/backend/uploads
    env_file:
      - ./.env
    restart: unless-stopped